export {default as Nav} from './Nav';
export {default as Header} from './Header';
export {default as SectionText} from './SectionText';
export {default as Services} from './Services';
export {default as Projects} from './Projects';
export {default as Skills} from './Skills';
export {default as Testimonial} from './Testimonial';
export {default as Contact} from './Contact';
export {default as Footer} from './Footer';